name: 'Telegram Message Notify Actions'
description: 'TNA уведомляет об изменениях в репозитории, ускоряя мониторинг и коммуникацию'
author: 'Digital-Life-71'
inputs:
  TELEGRAM_TOKEN:
    description: 'Токен Telegram'
    required: true
    default: ''
  TELEGRAM_CHAT_ID:
    description: 'ID чата Telegram'
    required: true
    default: ''
  TELEGRAM_MESSAGE:
    description: 'Сообщение для отправки'
    required: true
    default: |
      📝 Commit: ${{ github.event.head_commit.message }}
      ⚠️ Branch: ${{ github.ref_name }}
      👤 Author: ${{ github.actor }}
      📅 Date: ${{ github.event.head_commit.timestamp }}
      📂 Repository: ${{ github.repository }}
      🔗 Commit URL: ${{ github.event.head_commit.url }}
      🆔 Commit ID: ${{ github.sha }}
      🏷️ Repository Owner: ${{ github.repository_owner }}
      📛 Repository Name: ${{ github.event.repository.name }}
  BUTTON_TEXT:
    description: 'Текст кнопки'
    required: true
    default: 'Посмотреть'
  BUTTON_URL:
    description: 'URL кнопки'
    required: true
    default: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
  DISABLE_NOTIFICATION:
    description: 'Отключить уведомления'
    required: false
    default: 'true'
  COMMIT:
    description: 'Коммит'
    required: false
    default: ''
  BRANCH:
    description: 'Ветка'
    required: false
    default: ''
  AUTHOR:
    description: 'Автор'
    required: false
    default: ''
  DATE:
    description: 'Дата коммита'
    required: false
    default: ''
  REPOSITORY:
    description: 'Репозиторий'
    required: false
    default: ''
  COMMIT_URL:
    description: 'URL коммита'
    required: false
    default: ''
  COMMIT_ID:
    description: 'ID коммита'
    required: false
    default: ''
  REPOSITORY_OWNER:
    description: 'Владелец репозитория'
    required: false
    default: ''
  REPOSITORY_NAME:
    description: 'Имя репозитория'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Отправка сообщения в Telegram # Название шага
      shell: bash # Использование оболочки bash
      env:
        TELEGRAM_TOKEN: ${{ inputs.TELEGRAM_TOKEN }} # Установка переменной окружения TELEGRAM_TOKEN
        TELEGRAM_CHAT_ID: ${{ inputs.TELEGRAM_CHAT_ID }} # Установка переменной окружения TELEGRAM_CHAT_ID
        TELEGRAM_MESSAGE: ${{ inputs.TELEGRAM_MESSAGE }} # Установка переменной окружения TELEGRAM_MESSAGE
        BUTTON_TEXT: ${{ inputs.BUTTON_TEXT }} # Установка переменной окружения BUTTON_TEXT
        BUTTON_URL: ${{ inputs.BUTTON_URL }} # Установка переменной окружения BUTTON_URL
        DISABLE_NOTIFICATION: ${{ inputs.DISABLE_NOTIFICATION }} # Установка переменной окружения DISABLE_NOTIFICATION
        COMMIT: ${{ inputs.COMMIT }} # Установка переменной окружения COMMIT
        BRANCH: ${{ inputs.BRANCH }} # Установка переменной окружения BRANCH
        AUTHOR: ${{ inputs.AUTHOR }} # Установка переменной окружения AUTHOR
        DATE: ${{ inputs.DATE }} # Установка переменной окружения DATE
        REPOSITORY: ${{ inputs.REPOSITORY }} # Установка переменной окружения REPOSITORY
        COMMIT_URL: ${{ inputs.COMMIT_URL }} # Установка переменной окружения COMMIT_URL
        COMMIT_ID: ${{ inputs.COMMIT_ID }} # Установка переменной окружения COMMIT_ID
        REPOSITORY_OWNER: ${{ inputs.REPOSITORY_OWNER }} # Установка переменной окружения REPOSITORY_OWNER
        REPOSITORY_NAME: ${{ inputs.REPOSITORY_NAME }} # Установка переменной окружения REPOSITORY_NAME
      run: |
        set -e
        echo "Отправка сообщения в Telegram..."
        PAYLOAD="chat_id=${TELEGRAM_CHAT_ID}&text=${TELEGRAM_MESSAGE}&disable_notification=${DISABLE_NOTIFICATION}&reply_markup={\"inline_keyboard\":[[{\"text\":\"${BUTTON_TEXT}\",\"url\":\"${BUTTON_URL}\"}]]}"
        curl -v -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d "${PAYLOAD}"
